esphome:
  name: radiator-fans

esp8266:
  board: nodemcuv2

# Verbinding
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  min_auth_mode: WPA2

logger:
api:
ota:
  platform: esphome

# PWM output
output:
  - platform: esp8266_pwm
    pin: D1         # PWM signaal naar MOSFET of fan PWM input
    frequency: 20000 Hz  
    id: fan_pwm_output

# Fan component (slider + aan/uit)
fan:
  - platform: speed
    output: fan_pwm_output
    name: "Radiator Fans"
    id: radiator_fans
    speed_count: 50    # 0–100%
