esphome:
  name: radiator-fans

esp32:
  variant: esp32
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  min_auth_mode: WPA2

logger:
api:
ota:
  platform: esphome

web_server:
  port: 80

power_supply:
  - id: fan_power
    pin: GPIO23
    enable_time: 100ms
    keep_on_time: 0s

one_wire:
  - platform: gpio
    pin: GPIO4

sensor:
  - platform: dallas_temp
    name: "Radiator Temperatuur"
    update_interval: 20s

# PWM output
output:
  - platform: ledc
    pin: GPIO18
    frequency: 25000 Hz 
    id: fan_pwm_output
    power_supply: fan_power


fan:
  - platform: speed
    output: fan_pwm_output
    name: "Radiator Fans"
    id: radiator_fans
    speed_count: 100
